create table GAME_TYPE(
   ID INT NOT NULL AUTO_INCREMENT,
   TYPE VARCHAR(50) NOT NULL,
   DISPLAY_NAME VARCHAR(50) NOT NULL,
   PRIMARY KEY ( ID )
);
INSERT INTO GAME_TYPE(ID,TYPE,DISPLAY_NAME) VALUES (1,'SINGLES','Singles');
INSERT INTO GAME_TYPE(ID,TYPE,DISPLAY_NAME) VALUES (2,'DOUBLES','Doubles');
INSERT INTO GAME_TYPE(ID,TYPE,DISPLAY_NAME) VALUES (3,'MIXED_DOUBLES','Mixed Doubles');
INSERT INTO GAME_TYPE(ID,TYPE,DISPLAY_NAME) VALUES (4,'MIXED_SINGLES','Mixed Singles');
commit;