create table GAME_TYPE(
   
   GAME_TYPE_ID INT NOT NULL AUTO_INCREMENT,
   GAME_TYPE_NAME VARCHAR(50) NOT NULL,
   GAME_TYPE_DISPLAY_NAME VARCHAR(50) NOT NULL,
   CONSTRAINT GAME_TYPEC_PK  PRIMARY KEY ( GAME_TYPE_ID )
);
INSERT INTO GAME_TYPE(GAME_TYPE_ID,GAME_TYPE_NAME,GAME_TYPE_DISPLAY_NAME) VALUES (1,'SINGLES','Singles');
INSERT INTO GAME_TYPE(GAME_TYPE_ID,GAME_TYPE_NAME,GAME_TYPE_DISPLAY_NAME) VALUES (2,'DOUBLES','Doubles');
INSERT INTO GAME_TYPE(GAME_TYPE_ID,GAME_TYPE_NAME,GAME_TYPE_DISPLAY_NAME) VALUES (3,'MIXED_DOUBLES','Mixed Doubles');
INSERT INTO GAME_TYPE(GAME_TYPE_ID,GAME_TYPE_NAME,GAME_TYPE_DISPLAY_NAME) VALUES (4,'MIXED_SINGLES','Mixed Singles');


 CREATE TABLE CONNECTION_DETAILS    
   (
	   CONNECTION_ID INT NOT NULL , 
	   CONNECTION_NAME VARCHAR(50 )  NOT NULL  , 
	   JDBC_URL  VARCHAR(500 ),
	   HOST_NAME VARCHAR(100 )  NOT NULL  , 
	   PORT_NO INT NOT NULL ,
	   SERVICE_NAME VARCHAR(50 )  NOT NULL  ,
	   USER_ID VARCHAR(50 )  NOT NULL  ,
	   ENCRYPTED_PASSWORD VARCHAR(250 )  NOT NULL  , 
	   DRIVER_NAME VARCHAR(500 )  NOT NULL  , 
	   FL_ACTIVE INT DEFAULT 0, 
	   COMMENTS VARCHAR(500 )  ,
	   CONSTRAINT CONNECTION_DETAILS_PK PRIMARY KEY (CONNECTION_ID)
	   
   );

    INSERT INTO CONNECTION_DETAILS(CONNECTION_ID,CONNECTION_NAME,JDBC_URL,HOST_NAME,PORT_NO,SERVICE_NAME,USER_ID,ENCRYPTED_PASSWORD,DRIVER_NAME,FL_ACTIVE,COMMENTS)
values(1
,'DBTENNIS','jdbc:mysql://tennis.cnx63aff1prh.us-east-1.rds.amazonaws.com:3306/tennis','tennis.cnx63aff1prh.us-east-1.rds.amazonaws.com'
,'3306','tennis','admin','tennis123','com.mysql.jdbc.Driver',1,null);

CREATE TABLE ADDRESS    
   (
	   ADDRESS_ID INT NOT NULL , 
	   STREET_ADDRESS_1 VARCHAR(255 )  NOT NULL  , 
	   STREET_ADDRESS_2 VARCHAR(255 )    ,
	   CITY VARCHAR(100 )  NOT NULL  ,
	   STATE VARCHAR(100 )  NOT NULL ,
	   COUNTRY VARCHAR(100 )  NOT NULL  ,
	   ZIP INT (9 )  NOT NULL ,
	   CONSTRAINT ADDRESS_PK PRIMARY KEY (ADDRESS_ID)
	   
   );

CREATE TABLE MEDIA    
   (
	   MEDIA_INTERNAL_ID INT NOT NULL,
	   MEDIA_ID INT NOT NULL , 
	   IMG_LINK VARCHAR(500 )   , 
	   VIDEO_LINK VARCHAR(500 )    ,
	   COMMENTS VARCHAR(500 )  ,
	   CONSTRAINT MEDIA_PK PRIMARY KEY (MEDIA_INTERNAL_ID)
   );

   CREATE INDEX MEDIA_ID_IDX ON MEDIA (MEDIA_ID);
   

   	CREATE TABLE COURT_TYPE    
   (
	   COURT_TYPE_ID INT NOT NULL , 
	   COURT_TYPE_NAME VARCHAR(500 )   , 
	   COURT_TYPE_DISPLAY_NAME VARCHAR(500 ), 
	   CONSTRAINT COURT_TYPE_PK PRIMARY KEY (COURT_TYPE_ID)
	   
   );
   
   INSERT INTO COURT_TYPE(COURT_TYPE_ID,COURT_TYPE_NAME,COURT_TYPE_DISPLAY_NAME) VALUES(1,'HARD', 'Hard');
   INSERT INTO COURT_TYPE(COURT_TYPE_ID,COURT_TYPE_NAME,COURT_TYPE_DISPLAY_NAME) VALUES(2,'CLAY', 'Clay');
   INSERT INTO COURT_TYPE(COURT_TYPE_ID,COURT_TYPE_NAME,COURT_TYPE_DISPLAY_NAME) VALUES(3,'GRASS', 'Grass');
 

 	
	CREATE TABLE ACCESS_TYPE    
   (
	   ACCESS_TYPE_ID INT NOT NULL , 
	   ACCESS_TYPE_NAME VARCHAR(50 )   , 

	   CONSTRAINT ACCESS_TYPE_PK PRIMARY KEY (ACCESS_TYPE_ID)
	   
   );
   
   INSERT INTO ACCESS_TYPE(ACCESS_TYPE_ID,ACCESS_TYPE_NAME) VALUES(1,'PUBLIC');
    INSERT INTO ACCESS_TYPE(ACCESS_TYPE_ID,ACCESS_TYPE_NAME)  VALUES(2,'PRIVATE');



      
   CREATE TABLE COURT_RATING   
   (
	   COURT_RATING_ID INT NOT NULL , 
	   COURT_RATING_NAME VARCHAR(50 ) , 
	   COURT_RATING_VALUE VARCHAR(5 ) , 

	   CONSTRAINT COURT_RATING_PK PRIMARY KEY (COURT_RATING_ID)
	   
   );

   INSERT INTO COURT_RATING(COURT_RATING_ID,COURT_RATING_NAME,COURT_RATING_VALUE) VALUES(1,'ONE','*');
   INSERT INTO COURT_RATING(COURT_RATING_ID,COURT_RATING_NAME,COURT_RATING_VALUE) VALUES(2,'TWO','**');
   INSERT INTO COURT_RATING(COURT_RATING_ID,COURT_RATING_NAME,COURT_RATING_VALUE) VALUES(3,'THREE','***');
   INSERT INTO COURT_RATING(COURT_RATING_ID,COURT_RATING_NAME,COURT_RATING_VALUE) VALUES(4,'FOUR','****');
   INSERT INTO COURT_RATING(COURT_RATING_ID,COURT_RATING_NAME,COURT_RATING_VALUE) VALUES(5,'FIVE','*****');

   CREATE TABLE COURT    
   (
	   COURT_ID INT NOT NULL , 
	   COURT_NAME VARCHAR(50 ) NOT NULL  , 
	  ADDRESS_ID INT NOT NULL ,
	   ACTIVE INT(1 ) DEFAULT 1 ,
	   COURT_TYPE_ID INT NOT NULL ,
	   ACCESS_TYPE_ID INT NOT NULL ,
	   COURT_RATING_ID INT NOT NULL DEFAULT 3,
	   CONSTRAINT COURT_PK PRIMARY KEY (COURT_ID),
	   CONSTRAINT COURT_ADDRESS_FK FOREIGN KEY (ADDRESS_ID)  REFERENCES ADDRESS(ADDRESS_ID),
	   CONSTRAINT COURT_COURT_TYPE_FK FOREIGN KEY (COURT_TYPE_ID)  REFERENCES COURT_TYPE(COURT_TYPE_ID),
	   CONSTRAINT COURT_ACCESS_TYPE_FK FOREIGN KEY (ACCESS_TYPE_ID)  REFERENCES ACCESS_TYPE(ACCESS_TYPE_ID),
	   CONSTRAINT COURT_COURT_RATING_ID_FK FOREIGN KEY (COURT_RATING_ID)  REFERENCES COURT_RATING(COURT_RATING_ID)
	   
   )

   CREATE TABLE MATCH_TYPE    
   (
	   MATCH_TYPE_ID INT(1) NOT NULL , 
	   MATCH_TYPE_NAME VARCHAR(50 ) NOT NULL  , 
	   MATCH_TYPE_DISPLAY_NAME VARCHAR(50 ) NOT NULL  , 
	   CONSTRAINT MATCH_TYPE_PK PRIMARY KEY (MATCH_TYPE_ID)
	   
   )
   
   INSERT INTO MATCH_TYPE(MATCH_TYPE_ID,MATCH_TYPE_NAME,MATCH_TYPE_DISPLAY_NAME) VALUES (1,'REGULAR','Singles');
   INSERT INTO MATCH_TYPE(MATCH_TYPE_ID,MATCH_TYPE_NAME,MATCH_TYPE_DISPLAY_NAME) VALUES (2,'TOURNAMENT_LEAGUE','Tournament League');
   INSERT INTO MATCH_TYPE(MATCH_TYPE_ID,MATCH_TYPE_NAME,MATCH_TYPE_DISPLAY_NAME) VALUES (3,'TOURNAMENT_PLAYOFF','Tournament Playoff');

 CREATE TABLE RESULT_TYPE    
   (
	   RESULT_TYPE_ID INT(1) NOT NULL , 
	   RESULT_TYPE_NAME VARCHAR(50 ) NOT NULL  , 
	   RESULT_TYPE_DISPLAY_NAME VARCHAR(50 ) NOT NULL  , 
	   CONSTRAINT MATCH_TYPE_PK PRIMARY KEY (RESULT_TYPE_ID)
	   
   )
   
   INSERT INTO RESULT_TYPE(RESULT_TYPE_ID,RESULT_TYPE_NAME,RESULT_TYPE_DISPLAY_NAME) VALUES (1,'COMPLETED','Completed');
   INSERT INTO RESULT_TYPE(RESULT_TYPE_ID,RESULT_TYPE_NAME,RESULT_TYPE_DISPLAY_NAME)  VALUES (2,'NOT_COMPLETED','Not Completed');
   INSERT INTO RESULT_TYPE(RESULT_TYPE_ID,RESULT_TYPE_NAME,RESULT_TYPE_DISPLAY_NAME)  VALUES (3,'NOT_STARTED','Not Started');




      CREATE TABLE SEX(
 
	   SEX_NAME VARCHAR(50 ) NOT NULL  , 
	   SEX_DISPLAY_NAME VARCHAR(50 ) NOT NULL  ,
	   CONSTRAINT SEX_PK PRIMARY KEY (SEX_NAME)
	   
   )
   
   INSERT INTO SEX(SEX_NAME,SEX_DISPLAY_NAME) VALUES ('MALE','Male');
   INSERT INTO SEX(SEX_NAME,SEX_DISPLAY_NAME) VALUES ('FEMALE','Female');

   CREATE TABLE PLAYER    
   (
	   PLAYER_ID INT NOT NULL , 
	   USER_NAME VARCHAR(25) NOT NULL ,
	    PASSWORD VARCHAR(25) NOT NULL ,
	    FIRST_NAME VARCHAR(50 ) NOT NULL  , 
	    LAST_NAME VARCHAR(50 ) NOT NULL  , 
	    EMAIL_ID VARCHAR(50 ) NOT NULL  , 
	    PHONE_NO VARCHAR(15) NOT NULL,
        ADDRESS_ID INT NOT NULL , 
	    SEX_NAME VARCHAR(50 ) NOT NULL DEFAULT 'MALE' , 
	    MEDIA_ID INT,
	    DESCRIPTION VARCHAR(500),
	    LEVEL DECIMAL(1,1) , 
	    TOURNAMENT_WON INT ,         
 		REG_MATCH_PLAYED INT ,       
 		REG_MATCH_WON INT  ,         
 		REG_MATCH_DRAWN INT  ,       
 		TOURNAMENT_MATCH_PLAYED INT ,
 		TOURNAMENT_MATCH_WON INT  ,  
 		TOURNAMENT_MATCH_DRAWN INT  ,
	   RAITNG INT,
	   TOURNAMENT_RAITNG INT,
	   CONSTRAINT PLAYER_PK PRIMARY KEY (PLAYER_ID),   
	   CONSTRAINT PLAYER_MEDIA_FK FOREIGN KEY (MEDIA_ID)  REFERENCES MEDIA(MEDIA_ID),
	   CONSTRAINT PLAYER_ADDRESS_ID_FK FOREIGN KEY (ADDRESS_ID)  REFERENCES ADDRESS(ADDRESS_ID),
	    CONSTRAINT PLAYER_SEX_NAME_FK FOREIGN KEY (SEX_NAME)  REFERENCES SEX(SEX_NAME)
   )

    CREATE TABLE SCHEDULE    
   (
	   SCHEDULE_ID INT NOT NULL , 
	   FROM_DATE DATETIME  NOT NULL, 
	   TO_DATE DATETIME  NOT NULL, 
	   COURT_ID INT,
	   CONSTRAINT SCHEDULE_PK PRIMARY KEY (SCHEDULE_ID),
	   CONSTRAINT SCHEDULE_COURT_FK FOREIGN KEY (COURT_ID)  REFERENCES COURT(COURT_ID)
	   
   )

    CREATE TABLE SCORE    
   (
	   SCORE_ID INT NOT NULL , 
	   WINNER_PLAYER_ID INT NOT NULL, 
	   RUNNER_PLAYER_ID INT NOT NULL, 
	   WINNER_SET1_SCORE INT,
	   RUNNER_SET1_SCORE INT,
	   DURATION_SET1_MINS INT,
	   WINNER_SET2_SCORE INT,
	   RUNNER_SET2_SCORE INT,
	   DURATION_SET2_MINS INT,
	   WINNER_SET3_SCORE INT,
	   RUNNER_SET3_SCORE INT,
	   DURATION_SET3_MINS INT,
	   WINNER_SET4_SCORE INT,
	   RUNNER_SET4_SCORE INT,
	   DURATION_SET4_MINS INT,
	   WINNER_SET5_SCORE INT,
	   RUNNER_SET5_SCORE INT,
	   DURATION_SET5_MINS INT,
	   CONSTRAINT SCORE_ID PRIMARY KEY (SCORE_ID),
	   CONSTRAINT SCORE_PLAYER_FK1 FOREIGN KEY (WINNER_PLAYER_ID)  REFERENCES PLAYER(PLAYER_ID),
	    CONSTRAINT SCORE_PLAYER_FK2 FOREIGN KEY (RUNNER_PLAYER_ID)  REFERENCES PLAYER(PLAYER_ID)
	   
   )

       CREATE TABLE SCHEDULE_LOGIC    
   (
	   SCHEDULE_LOGIC_ID INT NOT NULL , 
	   SCHEDULE_LOGIC_NAME VARCHAR(50 ) NOT NULL  , 
	   SCHEDULE_LOGIC_DISPLAY_NAME VARCHAR(50 ) NOT NULL  , 
	   CONSTRAINT SCHEDULE_LOGIC_PK PRIMARY KEY (SCHEDULE_LOGIC_ID)
	   
   )
   
      INSERT INTO SCHEDULE_LOGIC(SCHEDULE_LOGIC_ID,SCHEDULE_LOGIC_NAME,SCHEDULE_LOGIC_DISPLAY_NAME) VALUES (1,'ROUND_ROBIN','Round Robin');
      INSERT INTO SCHEDULE_LOGIC(SCHEDULE_LOGIC_ID,SCHEDULE_LOGIC_NAME,SCHEDULE_LOGIC_DISPLAY_NAME) VALUES (2,'SINGLE_ELIMINATION','Single Elimination');


   CREATE TABLE TOURNAMENT    
   (
	   TOURNAMENT_ID INT NOT NULL , 
	   TOURNAMENT_NAME VARCHAR(100) NOT NULL,
	   PRIZE_1ST INT , 
	   PRIZE_2ND INT , 
	   PRIZE_3RD INT , 
	   ENTREE_FEE INT ,
	   WINNER_ID INT, 
	   RUNNER_ID INT ,
	   SCHEDULE_LOGIC_ID INT,
	  
	   CONSTRAINT TOURNAMENT_PK PRIMARY KEY (TOURNAMENT_ID),
	   CONSTRAINT TOURNAMENT_PLAYER_FK1 FOREIGN KEY (WINNER_ID)  REFERENCES PLAYER(PLAYER_ID),
	    CONSTRAINT TOURNAMENT_PLAYER_FK2 FOREIGN KEY (RUNNER_ID)  REFERENCES PLAYER(PLAYER_ID),
		CONSTRAINT TOURNAMENT_SCHEDULE_LOGIC_ID_FK FOREIGN KEY (SCHEDULE_LOGIC_ID) REFERENCES SCHEDULE_LOGIC(SCHEDULE_LOGIC_ID)
	   
   )

 CREATE TABLE MATCH_DETAILS    
   (
	   MATCH_ID INT NOT NULL , 
	   MATCH_NAME VARCHAR(50) NOT NULL,
	   PLAYER_ID_1 INT NOT NULL, 
	   PLAYER_ID_2 INT NOT NULL, 
	   PLAYER_ID_3 INT ,
	   PLAYER_ID_4 INT ,
	   MATCH_TYPE_ID INT(1) NOT NULL DEFAULT 1,
	   GAME_TYPE_ID INT  NOT NULL DEFAULT 1,
	    RESULT_TYPE_ID INT(1) ,
	   SCORE_ID INT,
	   TOURNAMENT_ID INT,
	   COMMENT VARCHAR(500),
	   COURT_ID INT,
	   SCHEDULE_ID_1 INT,
	    SCHEDULE_ID_2 INT,
	     SCHEDULE_ID_3 INT,
	   MEDIA_ID INT,
	   PLAYED_TIME DATETIME,
	   CREATED_TIME DATETIME,
	   CONSTRAINT MATCH_ID PRIMARY KEY (MATCH_ID),
	   CONSTRAINT MATCH_PLAYER_FK1 FOREIGN KEY (PLAYER_ID_1)  REFERENCES PLAYER(PLAYER_ID),
	   CONSTRAINT MATCH_PLAYER_FK2 FOREIGN KEY (PLAYER_ID_2)  REFERENCES PLAYER(PLAYER_ID),
	   CONSTRAINT MATCH_PLAYER_FK3 FOREIGN KEY (PLAYER_ID_3)  REFERENCES PLAYER(PLAYER_ID),
	   CONSTRAINT MATCH_PLAYER_FK4 FOREIGN KEY (PLAYER_ID_4)  REFERENCES PLAYER(PLAYER_ID),
	    CONSTRAINT MATCH_MATCH_TYPE_FK FOREIGN KEY (MATCH_TYPE_ID)  REFERENCES MATCH_TYPE(MATCH_TYPE_ID),
	    CONSTRAINT MATCH_RESULT_TYPE_FK FOREIGN KEY (RESULT_TYPE_ID)  REFERENCES RESULT_TYPE(RESULT_TYPE_ID),
	    CONSTRAINT MATCH_SCORE_FK FOREIGN KEY (SCORE_ID)  REFERENCES SCORE(SCORE_ID),
	    CONSTRAINT MATCH_TOURNAMENT_FK FOREIGN KEY (TOURNAMENT_ID)  REFERENCES TOURNAMENT(TOURNAMENT_ID),
	     CONSTRAINT MATCH_COURT_FK FOREIGN KEY (COURT_ID)  REFERENCES COURT(COURT_ID),
	      CONSTRAINT MATCH_MEDIA_ID_FK FOREIGN KEY (MEDIA_ID)  REFERENCES MEDIA(MEDIA_ID),
	      CONSTRAINT MATCH_SCHEDULE_ID_FK1 FOREIGN KEY (SCHEDULE_ID_1)  REFERENCES SCHEDULE(SCHEDULE_ID),
	      CONSTRAINT MATCH_SCHEDULE_ID_FK2 FOREIGN KEY (SCHEDULE_ID_2)  REFERENCES SCHEDULE(SCHEDULE_ID),
	      CONSTRAINT MATCH_SCHEDULE_ID_FK3 FOREIGN KEY (SCHEDULE_ID_3)  REFERENCES SCHEDULE(SCHEDULE_ID),
		  CONSTRAINT MATCH_GAME_TYPE_ID_FK FOREIGN KEY (GAME_TYPE_ID) REFERENCES GAME_TYPE(GAME_TYPE_ID)
	   
   )


CREATE TABLE TOURNAMENT_PLAYER_DETAILS   
   (
	   TOURNAMENT_PLAYER_ID INT NOT NULL , 
	   TOURNAMENT_ID INT NOT NULL , 
	   PLAYER_ID INT NOT NULL , 
	   RANKING INT,
	   MATCH_WON INT , 
	   MATCH_LOST INT , 
	   SET_WON INT , 
	   SET_LOST INT ,
	   GAME_WON INT, 
	   GAME_LOST INT ,
	  
	  
	   CONSTRAINT TOURNAMENT_PLAYER_DETAILS_PK PRIMARY KEY (TOURNAMENT_PLAYER_ID),
	   CONSTRAINT TOURNAMENT_PLAYER_TOURNAMENT_ID_FK FOREIGN KEY (TOURNAMENT_ID)  REFERENCES TOURNAMENT(TOURNAMENT_ID),
	    CONSTRAINT TOURNAMENT_PLAYER_PLAYER_ID_FK FOREIGN KEY (PLAYER_ID)  REFERENCES PLAYER(PLAYER_ID)
	   
   )
 
 
 commit;