DROP TABLE REPORT_DATA_FIELDS;
DROP TABLE REPORT_DATA_SOURCES;
DROP TABLE REPORT_FILTER_TYPE;
DROP TABLE REPORT_FILTER_OPERATORS;

  CREATE TABLE "REPORT_DATA_SOURCES" 
   (
    "REPORT_INTERNAL_ID" NUMBER(9,0) NOT NULL ENABLE, 
	"REPORT_IDENTIFIER" VARCHAR2(255 BYTE) NOT NULL ENABLE, 
	"DISPLAY_NAME" VARCHAR2(255 BYTE) NOT NULL ENABLE, 
	"REPORT_DESCRIPTION" VARCHAR2(1000 BYTE), 
	"VIEW_NAME" VARCHAR2(255 BYTE), 	
	"DISPLAY_ORDER" NUMBER NOT NULL ENABLE, 
	"CREATED_DATE" DATE NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(255 BYTE), 
	"FL_DELETED" NUMBER(1,0) DEFAULT 0, 
	"CONNECTION_ID" NUMBER(9,0) NOT NULL ENABLE , 
	 CONSTRAINT "REPORT_DATA_SOURCES_PK" PRIMARY KEY ("REPORT_INTERNAL_ID"),
	 CONSTRAINT "REPORT_DATA_SRC_CONN_ID_FK" FOREIGN KEY ("CONNECTION_ID")  REFERENCES "REPORT_FILTER_TYPE" ("CONNECTION_ID") ENABLE
   );
   
   
    CREATE TABLE "REPORT_DATA_FIELDS" 
   (	
   "REPORT_FIELDS_INTERNAL_ID" NUMBER(9,0) NOT NULL ENABLE, 
	"REPORT_INTERNAL_ID" NUMBER(9,0) NOT NULL ENABLE, 
	"FIELD_NAME" VARCHAR2(255 BYTE) NOT NULL ENABLE, 
	"DISPLAY_NAME" VARCHAR2(255 BYTE) NOT NULL ENABLE, 
	"FIELD_TYPE" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"FIELD_LENGTH" NUMBER(9,0) NOT NULL ENABLE, 
	"DISPLAY_ORDER" NUMBER NOT NULL ENABLE, 
	"FL_HIDE" NUMBER(1,0) DEFAULT 0, 
	"FL_PERIOD" NUMBER(1,0) NOT NULL ENABLE, 
	"FL_DEFAULTSORT" NUMBER(1,0) DEFAULT 0, 
	"FL_FILTER" NUMBER(1,0) DEFAULT 1, 
	 CONSTRAINT "REPORT_DATA_FIELDS_PK" PRIMARY KEY ("REPORT_FIELDS_INTERNAL_ID"),
	 CONSTRAINT "FK_REPORT_DATA_FIELDS" FOREIGN KEY ("REPORT_INTERNAL_ID")  REFERENCES "REPORT_DATA_SOURCES" ("REPORT_INTERNAL_ID") ENABLE
	 
   );

   CREATE TABLE "REPORT_FILTER_TYPE" 
   (
	   "FILTER_TYPE_ID" NUMBER(9,0) NOT NULL ENABLE, 
	   "FILTER_TYPE" VARCHAR2(50 BYTE)  NOT NULL ENABLE , 
	   "FILTER_NAME" VARCHAR2(50 BYTE)  NOT NULL ENABLE , 
	   "FL_ACTIVE" NUMBER(1,0) DEFAULT 0,
	    CONSTRAINT "REPORT_FILTER_TYPE_PK" PRIMARY KEY ("FILTER_TYPE_ID")
   );
   CREATE TABLE "REPORT_FILTER_OPERATORS" 
   (
	   "FILTER_OPR_ID" NUMBER(9,0) NOT NULL ENABLE, 
	   "FILTER_OPR_VALUE" VARCHAR2(50 BYTE)  NOT NULL ENABLE, 
	   "FILTER_OPR_DISPLAY_NAME" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	   	"FILTER_TYPE_ID" NUMBER(9,0) NOT NULL ENABLE, 
		"FL_ACTIVE" NUMBER(1,0) DEFAULT 0,
		CONSTRAINT "RPT_FLT_OPR_PK" PRIMARY KEY ("FILTER_OPR_ID"),
		CONSTRAINT "RPT_FLT_OPR_FLT_TYP_ID_FK" FOREIGN KEY ("FILTER_TYPE_ID")  REFERENCES "REPORT_FILTER_TYPE" ("FILTER_TYPE_ID") ENABLE
   );

   CREATE TABLE "CONNECTION_DETAILS" 
   (
	   "CONNECTION_ID" NUMBER(9,0) NOT NULL ENABLE, 
	   "CONNECTION_NAME" VARCHAR2(50 BYTE)  NOT NULL ENABLE , 
	   "JDBC_URL"  VARCHAR2(500 BYTE),
	   "HOST_NAME" VARCHAR2(100 BYTE)  NOT NULL ENABLE ,
	   "PORT_NO" NUMBER(9,0) NOT NULL ENABLE,
	   "SERVICE_NAME" VARCHAR2(50 BYTE)  NOT NULL ENABLE ,
	   "USER_ID" VARCHAR2(50 BYTE)  NOT NULL ENABLE ,
	   "ENCRYPTED_PASSWORD" VARCHAR2(250 BYTE)  NOT NULL ENABLE , 
	   "DRIVER_NAME" VARCHAR2(500 BYTE)  NOT NULL ENABLE , 
	   "FL_ACTIVE" NUMBER(1,0) DEFAULT 0, 
	   "COMMENTS" VARCHAR2(500 BYTE)  ,
	   CONSTRAINT "CONNECTION_DETAILS_PK" PRIMARY KEY ("CONNECTION_ID")
	   
   );

INSERT INTO "CADENT"."REPORT_FILTER_TYPE"(FILTER_TYPE_ID, FILTER_TYPE, FILTER_NAME) VALUES ((select Nvl(max(FILTER_TYPE_ID),0)+1 from REPORT_FILTER_TYPE), 'NUMBER', 'Number'); 
INSERT INTO "CADENT"."REPORT_FILTER_TYPE"(FILTER_TYPE_ID, FILTER_TYPE, FILTER_NAME) VALUES ((select Nvl(max(FILTER_TYPE_ID),0)+1 from REPORT_FILTER_TYPE), 'STRING', 'String'); 
INSERT INTO "CADENT"."REPORT_FILTER_TYPE"(FILTER_TYPE_ID, FILTER_TYPE, FILTER_NAME) VALUES ((select Nvl(max(FILTER_TYPE_ID),0)+1 from REPORT_FILTER_TYPE), 'DATE', 'Date'); 
INSERT INTO "CADENT"."REPORT_FILTER_TYPE"(FILTER_TYPE_ID, FILTER_TYPE, FILTER_NAME) VALUES ((select Nvl(max(FILTER_TYPE_ID),0)+1 from REPORT_FILTER_TYPE), 'TIMESTAMP', 'TimeStamp'); 

INSERT INTO "CADENT"."REPORT_FILTER_OPERATORS" (FILTER_OPR_ID, FILTER_OPR_VALUE, FILTER_OPR_DISPLAY_NAME,FILTER_TYPE_ID) VALUES ((select Nvl(max(FILTER_OPR_ID),0)+1 from REPORT_FILTER_OPERATORS),'=' ,'Equals', (select filter_type_id from REPORT_FILTER_TYPE where FILTER_TYPE='NUMBER'));
INSERT INTO "CADENT"."REPORT_FILTER_OPERATORS" (FILTER_OPR_ID, FILTER_OPR_VALUE, FILTER_OPR_DISPLAY_NAME,FILTER_TYPE_ID) VALUES ((select Nvl(max(FILTER_OPR_ID),0)+1 from REPORT_FILTER_OPERATORS),'!=' ,'Not Equals', (select filter_type_id from REPORT_FILTER_TYPE where FILTER_TYPE='NUMBER'));
INSERT INTO "CADENT"."REPORT_FILTER_OPERATORS" (FILTER_OPR_ID, FILTER_OPR_VALUE, FILTER_OPR_DISPLAY_NAME,FILTER_TYPE_ID) VALUES ((select Nvl(max(FILTER_OPR_ID),0)+1 from REPORT_FILTER_OPERATORS),'>' ,'Greater Than', (select filter_type_id from REPORT_FILTER_TYPE where FILTER_TYPE='NUMBER'));
INSERT INTO "CADENT"."REPORT_FILTER_OPERATORS" (FILTER_OPR_ID, FILTER_OPR_VALUE, FILTER_OPR_DISPLAY_NAME,FILTER_TYPE_ID) VALUES ((select Nvl(max(FILTER_OPR_ID),0)+1 from REPORT_FILTER_OPERATORS),'>=' ,'Greater Than or Equal To', (select filter_type_id from REPORT_FILTER_TYPE where FILTER_TYPE='NUMBER'));
INSERT INTO "CADENT"."REPORT_FILTER_OPERATORS" (FILTER_OPR_ID, FILTER_OPR_VALUE, FILTER_OPR_DISPLAY_NAME,FILTER_TYPE_ID) VALUES ((select Nvl(max(FILTER_OPR_ID),0)+1 from REPORT_FILTER_OPERATORS),'<' ,'Less Than', (select filter_type_id from REPORT_FILTER_TYPE where FILTER_TYPE='NUMBER'));
INSERT INTO "CADENT"."REPORT_FILTER_OPERATORS" (FILTER_OPR_ID, FILTER_OPR_VALUE, FILTER_OPR_DISPLAY_NAME,FILTER_TYPE_ID) VALUES ((select Nvl(max(FILTER_OPR_ID),0)+1 from REPORT_FILTER_OPERATORS),'<=' ,'Less Than or Equal to', (select filter_type_id from REPORT_FILTER_TYPE where FILTER_TYPE='NUMBER'));
INSERT INTO "CADENT"."REPORT_FILTER_OPERATORS" (FILTER_OPR_ID, FILTER_OPR_VALUE, FILTER_OPR_DISPLAY_NAME,FILTER_TYPE_ID) VALUES ((select Nvl(max(FILTER_OPR_ID),0)+1 from REPORT_FILTER_OPERATORS),'IS NULL' ,'Is Null', (select filter_type_id from REPORT_FILTER_TYPE where FILTER_TYPE='NUMBER'));
INSERT INTO "CADENT"."REPORT_FILTER_OPERATORS" (FILTER_OPR_ID, FILTER_OPR_VALUE, FILTER_OPR_DISPLAY_NAME,FILTER_TYPE_ID) VALUES ((select Nvl(max(FILTER_OPR_ID),0)+1 from REPORT_FILTER_OPERATORS),'IS NOT NULL' ,'Is Not Null', (select filter_type_id from REPORT_FILTER_TYPE where FILTER_TYPE='NUMBER'));


INSERT INTO "CADENT"."REPORT_FILTER_OPERATORS" (FILTER_OPR_ID, FILTER_OPR_VALUE, FILTER_OPR_DISPLAY_NAME,FILTER_TYPE_ID) VALUES ((select Nvl(max(FILTER_OPR_ID),0)+1 from REPORT_FILTER_OPERATORS),'=' ,'Equals', (select filter_type_id from REPORT_FILTER_TYPE where FILTER_TYPE='STRING'));
INSERT INTO "CADENT"."REPORT_FILTER_OPERATORS" (FILTER_OPR_ID, FILTER_OPR_VALUE, FILTER_OPR_DISPLAY_NAME,FILTER_TYPE_ID) VALUES ((select Nvl(max(FILTER_OPR_ID),0)+1 from REPORT_FILTER_OPERATORS),'!=' ,'Not Equals', (select filter_type_id from REPORT_FILTER_TYPE where FILTER_TYPE='STRING'));
INSERT INTO "CADENT"."REPORT_FILTER_OPERATORS" (FILTER_OPR_ID, FILTER_OPR_VALUE, FILTER_OPR_DISPLAY_NAME,FILTER_TYPE_ID) VALUES ((select Nvl(max(FILTER_OPR_ID),0)+1 from REPORT_FILTER_OPERATORS),'%%' ,'Like', (select filter_type_id from REPORT_FILTER_TYPE where FILTER_TYPE='STRING'));
INSERT INTO "CADENT"."REPORT_FILTER_OPERATORS" (FILTER_OPR_ID, FILTER_OPR_VALUE, FILTER_OPR_DISPLAY_NAME,FILTER_TYPE_ID) VALUES ((select Nvl(max(FILTER_OPR_ID),0)+1 from REPORT_FILTER_OPERATORS),'IS NULL' ,'Is Null', (select filter_type_id from REPORT_FILTER_TYPE where FILTER_TYPE='STRING'));
INSERT INTO "CADENT"."REPORT_FILTER_OPERATORS" (FILTER_OPR_ID, FILTER_OPR_VALUE, FILTER_OPR_DISPLAY_NAME,FILTER_TYPE_ID) VALUES ((select Nvl(max(FILTER_OPR_ID),0)+1 from REPORT_FILTER_OPERATORS),'IS NOT NULL' ,'Is Not Null', (select filter_type_id from REPORT_FILTER_TYPE where FILTER_TYPE='STRING'));


INSERT INTO "CADENT"."REPORT_FILTER_OPERATORS" (FILTER_OPR_ID, FILTER_OPR_VALUE, FILTER_OPR_DISPLAY_NAME,FILTER_TYPE_ID) VALUES ((select Nvl(max(FILTER_OPR_ID),0)+1 from REPORT_FILTER_OPERATORS),'=' ,'Equals', (select filter_type_id from REPORT_FILTER_TYPE where FILTER_TYPE='DATE'));
INSERT INTO "CADENT"."REPORT_FILTER_OPERATORS" (FILTER_OPR_ID, FILTER_OPR_VALUE, FILTER_OPR_DISPLAY_NAME,FILTER_TYPE_ID) VALUES ((select Nvl(max(FILTER_OPR_ID),0)+1 from REPORT_FILTER_OPERATORS),'!=' ,'Not Equals', (select filter_type_id from REPORT_FILTER_TYPE where FILTER_TYPE='DATE'));
INSERT INTO "CADENT"."REPORT_FILTER_OPERATORS" (FILTER_OPR_ID, FILTER_OPR_VALUE, FILTER_OPR_DISPLAY_NAME,FILTER_TYPE_ID) VALUES ((select Nvl(max(FILTER_OPR_ID),0)+1 from REPORT_FILTER_OPERATORS),'>' ,'Greater Than', (select filter_type_id from REPORT_FILTER_TYPE where FILTER_TYPE='DATE'));
INSERT INTO "CADENT"."REPORT_FILTER_OPERATORS" (FILTER_OPR_ID, FILTER_OPR_VALUE, FILTER_OPR_DISPLAY_NAME,FILTER_TYPE_ID) VALUES ((select Nvl(max(FILTER_OPR_ID),0)+1 from REPORT_FILTER_OPERATORS),'>=' ,'Greater Than or Equal To', (select filter_type_id from REPORT_FILTER_TYPE where FILTER_TYPE='DATE'));
INSERT INTO "CADENT"."REPORT_FILTER_OPERATORS" (FILTER_OPR_ID, FILTER_OPR_VALUE, FILTER_OPR_DISPLAY_NAME,FILTER_TYPE_ID) VALUES ((select Nvl(max(FILTER_OPR_ID),0)+1 from REPORT_FILTER_OPERATORS),'<' ,'Less Than', (select filter_type_id from REPORT_FILTER_TYPE where FILTER_TYPE='DATE'));
INSERT INTO "CADENT"."REPORT_FILTER_OPERATORS" (FILTER_OPR_ID, FILTER_OPR_VALUE, FILTER_OPR_DISPLAY_NAME,FILTER_TYPE_ID) VALUES ((select Nvl(max(FILTER_OPR_ID),0)+1 from REPORT_FILTER_OPERATORS),'<=' ,'Less Than or Equal to', (select filter_type_id from REPORT_FILTER_TYPE where FILTER_TYPE='DATE'));
INSERT INTO "CADENT"."REPORT_FILTER_OPERATORS" (FILTER_OPR_ID, FILTER_OPR_VALUE, FILTER_OPR_DISPLAY_NAME,FILTER_TYPE_ID) VALUES ((select Nvl(max(FILTER_OPR_ID),0)+1 from REPORT_FILTER_OPERATORS),'IS NULL' ,'Is Null', (select filter_type_id from REPORT_FILTER_TYPE where FILTER_TYPE='DATE'));
INSERT INTO "CADENT"."REPORT_FILTER_OPERATORS" (FILTER_OPR_ID, FILTER_OPR_VALUE, FILTER_OPR_DISPLAY_NAME,FILTER_TYPE_ID) VALUES ((select Nvl(max(FILTER_OPR_ID),0)+1 from REPORT_FILTER_OPERATORS),'IS NOT NULL' ,'Is Not Null', (select filter_type_id from REPORT_FILTER_TYPE where FILTER_TYPE='DATE'));
   
INSERT INTO "CADENT"."REPORT_DATA_SOURCES" (REPORT_INTERNAL_ID, REPORT_IDENTIFIER, DISPLAY_NAME, REPORT_DESCRIPTION, VIEW_NAME, DISPLAY_ORDER,CREATED_DATE, CREATED_BY) VALUES ((select Nvl(max(REPORT_INTERNAL_ID),0)+1 from REPORT_DATA_SOURCES), 'CX_NAM_METRICS', 'CX NAM METRICS', 'NAM Customer screening metrics ', 'CS_METRICS_SNAPSHOT', '100', sysdate, 'GOPU');
INSERT INTO "CADENT"."REPORT_DATA_SOURCES" (REPORT_INTERNAL_ID, REPORT_IDENTIFIER, DISPLAY_NAME, REPORT_DESCRIPTION, VIEW_NAME, DISPLAY_ORDER,CREATED_DATE, CREATED_BY) VALUES ((select Nvl(max(REPORT_INTERNAL_ID),0)+1 from REPORT_DATA_SOURCES), 'TX_NAM_METRICS', 'TX NAM METRICS', 'NAM Transaction Screening metrics ', 'TX_METRICS_SNAPSHOT', '101', sysdate, 'GOPU');
INSERT INTO "CADENT"."REPORT_DATA_SOURCES" (REPORT_INTERNAL_ID, REPORT_IDENTIFIER, DISPLAY_NAME, REPORT_DESCRIPTION, VIEW_NAME, DISPLAY_ORDER,CREATED_DATE, CREATED_BY) VALUES ((select Nvl(max(REPORT_INTERNAL_ID),0)+1 from REPORT_DATA_SOURCES), 'CX_EMEA_METRICS', 'CX EMEA METRICS', 'EMEA Customer screening metrics ', 'CX_EMEA_METRICS_SNAPSHOT', '102', sysdate, 'GOPU');
INSERT INTO "CADENT"."REPORT_DATA_SOURCES" (REPORT_INTERNAL_ID, REPORT_IDENTIFIER, DISPLAY_NAME, REPORT_DESCRIPTION, VIEW_NAME, DISPLAY_ORDER,CREATED_DATE, CREATED_BY) VALUES ((select Nvl(max(REPORT_INTERNAL_ID),0)+1 from REPORT_DATA_SOURCES), 'TX_EMEA_METRICS', 'TX EMEA METRICS', 'EEMA Transaction Screening metrics ', 'TX_EMEA_METRICS_SNAPSHOT', '103', sysdate, 'GOPU');
INSERT INTO "CADENT"."REPORT_DATA_SOURCES" (REPORT_INTERNAL_ID, REPORT_IDENTIFIER, DISPLAY_NAME, REPORT_DESCRIPTION, VIEW_NAME, DISPLAY_ORDER,CREATED_DATE, CREATED_BY) VALUES ((select Nvl(max(REPORT_INTERNAL_ID),0)+1 from REPORT_DATA_SOURCES), 'TX_APAC_METRICS', 'TX APAC METRICS', 'APAC Transaction Screening metrics ', 'TX_APAC_METRICS_SNAPSHOT', '104', sysdate, 'GOPU');
INSERT INTO "CADENT"."REPORT_DATA_SOURCES" (REPORT_INTERNAL_ID, REPORT_IDENTIFIER, DISPLAY_NAME, REPORT_DESCRIPTION, VIEW_NAME, DISPLAY_ORDER,CREATED_DATE, CREATED_BY) VALUES ((select Nvl(max(REPORT_INTERNAL_ID),0)+1 from REPORT_DATA_SOURCES), 'TX_MEX_METRICS', 'TX MEX METRICS', 'MEX Transaction Screening metrics ', 'TX_MEX_METRICS_SNAPSHOT', '105', sysdate, 'GOPU');


INSERT INTO REPORT_DATA_FIELDS (REPORT_FIELDS_INTERNAL_ID, REPORT_INTERNAL_ID, FIELD_NAME, DISPLAY_NAME, FIELD_TYPE, FIELD_LENGTH, DISPLAY_ORDER, FL_HIDE, FL_PERIOD, FL_DEFAULTSORT, FL_FILTER) VALUES ((select Nvl(max(REPORT_FIELDS_INTERNAL_ID),0)+1 from REPORT_DATA_FIELDS), '1', 'BUSINESS_UNIT_KEY', 'Business Unit Key', 'Integer', '10', '1', '0', '0', '0', '1')
INSERT INTO REPORT_DATA_FIELDS (REPORT_FIELDS_INTERNAL_ID, REPORT_INTERNAL_ID, FIELD_NAME, DISPLAY_NAME, FIELD_TYPE, FIELD_LENGTH, DISPLAY_ORDER, FL_HIDE, FL_PERIOD, FL_DEFAULTSORT, FL_FILTER) 	VALUES ((select Nvl(max(REPORT_FIELDS_INTERNAL_ID),0)+1 from REPORT_DATA_FIELDS),1,'BUSINESS_PRODUCT_ID','Business product Id','STRING',255,1,0,0,0,0)



INSERT INTO CADENT.CONNECTION_DETAILS(CONNECTION_ID,CONNECTION_NAME,JDBC_URL,HOST_NAME,PORT_NO,SERVICE_NAME,USER_ID,ENCRYPTED_PASSWORD,DRIVER_NAME,FL_ACTIVE,COMMENTS)
values((select Nvl(max(CONNECTION_ID),0)+1 from CONNECTION_DETAILS)
,'ANALYZER','jdbc:oracle:thin:@oraasswd14-scan.nam.nsroot.net:8889/CSANA1D','oraasswd14-scan.nam.nsroot.net'
,'8889','CSANA1D','CADENT','Madrid92','oracle.jdbc.OracleDriver',1,null);
INSERT INTO CADENT.CONNECTION_DETAILS(CONNECTION_ID,CONNECTION_NAME,JDBC_URL,HOST_NAME,PORT_NO,SERVICE_NAME,USER_ID,ENCRYPTED_PASSWORD,DRIVER_NAME,FL_ACTIVE,COMMENTS)
values((select Nvl(max(CONNECTION_ID),0)+1 from CONNECTION_DETAILS)
,'CITISEARCH','jdbc:oracle:thin:@oraasgtd34-scan.nam.nsroot.net:8889/CSFIN1D','oraasgtd34-scan.nam.nsroot.net'
,'8889','CSFIN1D','CSFIN_RCM_EXT','Puding10','oracle.jdbc.OracleDriver',1,null);
INSERT INTO CADENT.CONNECTION_DETAILS(CONNECTION_ID,CONNECTION_NAME,JDBC_URL,HOST_NAME,PORT_NO,SERVICE_NAME,USER_ID,ENCRYPTED_PASSWORD,DRIVER_NAME,FL_ACTIVE,COMMENTS)
values((select Nvl(max(CONNECTION_ID),0)+1 from CONNECTION_DETAILS)
,'CSAW_NAM_SIT','jdbc:oracle:thin:@sd-4d1a-b10e.nam.nsroot.net:1522/mstdb.nam.nsroot.net','sd-4d1a-b10e.nam.nsroot.net'
,'1522','mstdb.nam.nsroot.net','CADS','sdac1234','oracle.jdbc.OracleDriver',1,null);




commit;

create table GAME_TYPE(
   ID INT NOT NULL AUTO_INCREMENT,
   TYPE VARCHAR(50) NOT NULL,
   DISPLAY_NAME VARCHAR(50) NOT NULL,
   PRIMARY KEY ( ID )
);
INSERT INTO GAME_TYPE(ID,TYPE,DISPLAY_NAME) VALUES (1,'SINGLES','Singles');
INSERT INTO GAME_TYPE(ID,TYPE,DISPLAY_NAME) VALUES (2,'DOUBLES','Doubles');
INSERT INTO GAME_TYPE(ID,TYPE,DISPLAY_NAME) VALUES (3,'MIXED_DOUBLES','Mixed Doubles');
INSERT INTO GAME_TYPE(ID,TYPE,DISPLAY_NAME) VALUES (4,'MIXED_SINGLES','Mixed Singles');
commit;

 CREATE TABLE CONNECTION_DETAILS    
   (
	   CONNECTION_ID INT NOT NULL , 
	   CONNECTION_NAME VARCHAR(50 )  NOT NULL  , 
	   JDBC_URL  VARCHAR(500 ),
	   HOST_NAME VARCHAR(100 )  NOT NULL  ,
	   PORT_NO INT NOT NULL ,
	   SERVICE_NAME VARCHAR(50 )  NOT NULL  ,
	   USER_ID VARCHAR(50 )  NOT NULL  ,
	   ENCRYPTED_PASSWORD VARCHAR(250 )  NOT NULL  , 
	   DRIVER_NAME VARCHAR(500 )  NOT NULL  , 
	   FL_ACTIVE INT DEFAULT 0, 
	   COMMENTS VARCHAR(500 )  ,
	   CONSTRAINT CONNECTION_DETAILS_PK PRIMARY KEY (CONNECTION_ID)
	   
   );

    INSERT INTO CONNECTION_DETAILS(CONNECTION_ID,CONNECTION_NAME,JDBC_URL,HOST_NAME,PORT_NO,SERVICE_NAME,USER_ID,ENCRYPTED_PASSWORD,DRIVER_NAME,FL_ACTIVE,COMMENTS)
values(1
,'DBTENNIS','jdbc:mysql://tennis.cnx63aff1prh.us-east-1.rds.amazonaws.com:3306/tennis','tennis.cnx63aff1prh.us-east-1.rds.amazonaws.com'
,'3306','tennis','admin','tennis123','com.mysql.jdbc.Driver',1,null);

 